//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowAnalyzer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkflowAnalyzer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;{Assets}js/jquery-1.10.2.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;{Assets}js/jquery-ui-1.10.4.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;{Assets}js/jquery-ui-1.10.4.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;{Assets}js/BPA_JS.js&quot;&gt;&lt;/script&gt;
        ///&lt;link href=&quot;{Assets}css/ui-lightness/jquery-ui-1.10.4.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;link href=&quot;{Assets}css/ui-lightness/jquery-ui-1.10.4.min.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;link href=&quot;{Assets}css/BPA_CSS.css&quot; rel=&quot;stylesheet&quot; /&gt;.
        /// </summary>
        internal static string BPA_Assets {
            get {
                return ResourceManager.GetString("BPA_Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script src=&quot;{Assets}js/jquery-1.10.2.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;{Assets}js/jquery-ui-1.10.4.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;{Assets}js/jquery-ui-1.10.4.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;link href=&quot;{Assets}css/ui-lightness/jquery-ui-1.10.4.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;link href=&quot;{Assets}css/ui-lightness/jquery-ui-1.10.4.min.css&quot; rel=&quot;stylesheet&quot; /&gt;.
        /// </summary>
        internal static string JQuery {
            get {
                return ResourceManager.GetString("JQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintex Workflow Analyzer.
        /// </summary>
        internal static string WfaMain_aboutToolStripMenuItem_Click_Nintex_Workflow_Analyzer {
            get {
                return ResourceManager.GetString("WfaMain_aboutToolStripMenuItem_Click_Nintex_Workflow_Analyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string WfaMain_aboutToolStripMenuItem_Click_Version__ {
            get {
                return ResourceManager.GetString("WfaMain_aboutToolStripMenuItem_Click_Version__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nintex Workflow Analyzer - .
        /// </summary>
        internal static string WfaMain_LoadMainBrowserWithContent_Nintex_Workflow_Analyzer___ {
            get {
                return ResourceManager.GetString("WfaMain_LoadMainBrowserWithContent_Nintex_Workflow_Analyzer___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Issues.
        /// </summary>
        internal static string WfaMain_LoadWfbpaWithContent_Possible_Issues {
            get {
                return ResourceManager.GetString("WfaMain_LoadWfbpaWithContent_Possible_Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Configuration.
        /// </summary>
        internal static string WfaMain_LoadWfConfigurationWithContent_Workflow_Configuration {
            get {
                return ResourceManager.GetString("WfaMain_LoadWfConfigurationWithContent_Workflow_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Configuration.
        /// </summary>
        internal static string WfaMain_LoadWfExternalConfigurationWithContent_External_Configuration {
            get {
                return ResourceManager.GetString("WfaMain_LoadWfExternalConfigurationWithContent_External_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphical View.
        /// </summary>
        internal static string WfaMain_LoadWfGraphicalWithContent_Graphical_View {
            get {
                return ResourceManager.GetString("WfaMain_LoadWfGraphicalWithContent_Graphical_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Variables.
        /// </summary>
        internal static string WfaMain_LoadWfVariablesWithContent_Workflow_Variables {
            get {
                return ResourceManager.GetString("WfaMain_LoadWfVariablesWithContent_Workflow_Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External XML.
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_External_XML {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_External_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to render preview: .
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_Failed_to_render_preview__ {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_Failed_to_render_preview__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal XML.
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_Internal_XML {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_Internal_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_Preview {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Changes.
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_Preview_Changes {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_Preview_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Changes made to XML.
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_Preview_Changes_made_to_XML {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_Preview_Changes_made_to_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_Reset {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset XML to default.
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_Reset_XML_to_default {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_Reset_XML_to_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_Save {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to new NWF file..
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_Save_changes_to_new_NWF_file_ {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_Save_changes_to_new_NWF_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Editor.
        /// </summary>
        internal static string WfaMain_LoadXmlEditorWithContent_XML_Editor {
            get {
                return ResourceManager.GetString("WfaMain_LoadXmlEditorWithContent_XML_Editor", resourceCulture);
            }
        }
    }
}
